# Generated by Django 5.1.4 on 2025-01-08 22:24

import django.db.models.deletion
import farmacia.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[farmacia.validators.validate_alphabet])),
                ('lastName', models.CharField(max_length=100, validators=[farmacia.validators.validate_alphabet])),
                ('ci', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[farmacia.validators.validate_international_phone_number])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[farmacia.validators.validate_no_negative, farmacia.validators.validate_price_limit])),
                ('description', models.TextField(max_length=1000)),
                ('photo', models.CharField(max_length=1000)),
                ('stock', models.PositiveBigIntegerField(validators=[farmacia.validators.validate_stock_limit])),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[farmacia.validators.validate_no_negative])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[farmacia.validators.validate_no_negative])),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[farmacia.validators.validate_no_negative])),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicament')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.venta')),
            ],
        ),
    ]
